### ISSUE TITLE
Missing dependency?

### ISSUE THREAD

**Issue by bodograumann** [laggingreflex/npm-link-better#1]
When I try to run the command, I get the following error:

> module.js:550                                                                                                                                                                                
>     throw err;
>     ^
> 
> Error: Cannot find module 'debounce-queue'
>     at Function.Module._resolveFilename (module.js:548:15)
>     at Function.Module._load (module.js:475:25)
>     at Module.require (module.js:597:17)
>     at require (internal/module.js:11:18)
>     at Object.<anonymous> (/home/bodo/.local/lib64/node_modules/npm-link-better/lib/utils/index.js:9:18)
>     at Module._compile (module.js:653:30)
>     at Object.Module._extensions..js (module.js:664:10)
>     at Module.load (module.js:566:32)
>     at tryModuleLoad (module.js:506:12)
>     at Function.Module._load (module.js:498:3)

Is there a dependency missing, or is my node version too old?

> ╰┄┄> npm --version                                                                                                                                                                           
> 6.4.1                                                                                                                                                                                        
> ╰┄┄> node --version                                                                                                                                                                          
> v8.12.0

**Comment by laggingreflex** [comment]
Yep, dependency was missing. Fixed in https://github.com/laggingreflex/npm-link-better/commit/18eac9e4f975c43d6a22f2d24171e6aff8292ef8. Released v0.3.2
