### ISSUE TITLE
Feature request: add watch option

### ISSUE THREAD

**Issue by bodograumann** [laggingreflex/npm-link-better#2]
Could you add a `-w` / `--watch` to `nlc`, to automatically copy when a file is changed, like in `npm-link-copy`.

**Comment by bodograumann** [comment]
It would also be nice if in addition, there could be some output on the console when and where a change was detected.

**Comment by laggingreflex** [comment]
It already goes into watch mode by default, without the watch option.

**Comment by laggingreflex** [comment]
Introduced a mandatory `--watch`/`-w` flag to watch files instead of watching by default https://github.com/laggingreflex/npm-link-better/commit/e3a64c95347927db33df70edbcc0cd3d0b55b8bf Please update to v0.4.0
