### ISSUE TITLE
Error when using plain npm-link-better

### ISSUE THREAD

**Issue by bodograumann** [laggingreflex/npm-link-better#3]
When I try to run `npm-link-better` without any options, I get the following error:
                                                                                                                                          
> TypeError: Cannot read property '_' of undefined                                                                                                                                             
>     at module.exports (/home/bodo/.local/lib64/node_modules/npm-link-better/lib/quick/index.js:7:12)
>     at plain (/home/bodo/.local/lib64/node_modules/npm-link-better/lib/index.js:24:10)
>     at main (/home/bodo/.local/lib64/node_modules/npm-link-better/lib/index.js:18:8)
>     at Object.<anonymous> (/home/bodo/.local/lib64/node_modules/npm-link-better/bin/index.js:5:7)
>     at Module._compile (module.js:653:30)
>     at Object.Module._extensions..js (module.js:664:10)
>     at Module.load (module.js:566:32)
>     at tryModuleLoad (module.js:506:12)
>     at Function.Module._load (module.js:498:3)
>     at Function.Module.runMain (module.js:694:10)

**Comment by laggingreflex** [comment]
fixed in https://github.com/laggingreflex/npm-link-better/commit/66c815d3583ac52855f11a44ab480a2bf5aa81aa

**Comment by laggingreflex** [comment]
Actu
