### ISSUE TITLE
npm-link-better --copy --watch missing changes

### ISSUE THREAD

**Issue by bodograumann** [laggingreflex/npm-link-better#5]
When I'm adding changes to my linked project, they are not automatically copied.
That is unless they are in the main directory, afaics.

So maybe the `--watch` is not seeing changes in subdirectories?

**Comment by laggingreflex** [comment]
Ah, I'm using the native `fs.watch` which only seems to support `recursive` flag on Windows and Mac https://nodejs.org/docs/latest/api/fs.html#fs_caveats

I'll try and use some library...

**Comment by bodograumann** [comment]
That is too bad. I remember it working with your `npm-link-copy` though.

**Comment by laggingreflex** [comment]
Yeah, I was using https://github.com/paulmillr/chokidar. Will include it again.

**Comment by laggingreflex** [comment]
Fixed, try v0.4.3

**Comment by bodograumann** [comment]
Yes it works. Thank you so much!
